name: "DeepSAST"

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:

jobs:
  comprehensive-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para que TruffleHog vea el historial

      # 1. SEMGREP
      - name: Semgrep OSS Scan
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep \
          semgrep scan --config auto --sarif --output report-semgrep.sarif
        continue-on-error: true

      # 2. TRIVY (FS)
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true

      # 3. HORUSEC (Corregido el error 127)
      - name: Horusec Scan
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" -e="true" -o="text"
        continue-on-error: true

      # 4. TRUFFLEHOG (Ajustado para evitar error de Base/Head)
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: "" # Al dejarlo vacío escanea todo el repo, no solo el diff
          extra_args: --only-verified
        continue-on-error: true
